apiVersion: integration/v1
kind: Step
name: aws-sts-step-assume-role
version: 1
summary: Assume role
icon:

description: |
  Assumes the given role and returns the assumed credentials and role identifiers.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/aws-sts-step-assume-role

schemas:
  spec:
    source: file
    file: spec.schema.json
  output:
    source: file
    file: output.schema.json

examples:
  - summary: assume an STS role
    content:
      apiVersion: v1
      kind: Step
      name: assume-sts-role
      image: relaysh/aws-sts-step-assume-role
      spec:
        aws:
          connection: !Connection { type: aws, name: my-aws-account }
          region: !Parameter awsRegion
        roleARN: !Parameter roleArn
        roleSessionName: !Parameter roleSessionName
