apiVersion: integration/v1
kind: Integration
name: aws-sts
channel: stable
version: v20200408
summary: Amazon Web Services Security Token Service
license: Apache-2.0
homepage: https://github.com/relay-integrations/relay-aws-sts
source: git://github.com/relay-integrations/relay-aws-sts.git

description: |
    AWS STS is a web service that enables you to request temporary, limited-privilege
    credentials for AWS Identity and Access Management (IAM) users or for
    users that you authenticate (federated users).

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
  - aws
